name: Docker production backend build

on:
  push:
    tags:
      - 'v*_api'

jobs:
  build-autonomous-code-be-production:
    uses: autonomous-ai/github-templates/.github/workflows/docker-build-and-push.yaml@main
    with:
      DOCKER_IMAGE_NAME: autonomous-code-be
      DOCKER_CONTEXT: backend
      DOCKERFILE_NAME: Dockerfile.k8s
      CONCURRENCY_GROUP: docker_build_web_production
      RUNNER_TAG: ubuntu-latest
    secrets:
      GCLOUD_DEV_SERVICE_ACCOUNT_JSON: ${{ secrets.GCLOUD_DEV_SERVICE_ACCOUNT_JSON }}
